### ISSUE TITLE
cannot compatible with non-GUI system

### ISSUE THREAD

**Issue by smailzhu** [BreezeWhite/THSR-Ticket#5]
`UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.`

https://github.com/BreezeWhite/THSR-Ticket/blob/499359f24f02daa69acbe72d8e7396221c868899/thsr_ticket/controller/booking_flow.py#L136

```
./thsr_ticket/controller/booking_flow.py:136: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
^CTraceback (most recent call last):
  File "thsr_ticket/main.py", line 15, in <module>
    result = flow.run()
  File "./thsr_ticket/controller/booking_flow.py", line 52, in run
    self.book_form.security_code = self.input_security_code()
  File "./thsr_ticket/controller/booking_flow.py", line 137, in input_security_code
    return input()
```

**Comment by smailzhu** [comment]
Could if solved by show the verify image URL when client doesn't support GUI?

**Comment by BreezeWhite** [comment]
You can use `WebAgg` to show the verification code by opening the browser.
